### ISSUE TITLE
Can't start the skill - TypeError: '>' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by macxcool** [MycroftAI/skill-npr-news#123]
**Describe the bug**
Mycroft consistently fails to start this skill and throws a python error:
TypeError: '>' not supported between instances of 'list' and 'int'

**To Reproduce**
Install the news still and watch the logs. The skill never gets enabled.

**Log files**
`
19:34:08.038 | INFO     |   763 | NewsSkill | Creating custom News Station from Skill settings.
~~~~ate_skill_instance:313 | Skill initialization failed with TypeError("'>' not supported between instances of 'list' and 'int'")Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/skill_loader.py", line 307, in _create_skill_instance
    self.instance.initialize()
  File "/opt/mycroft/skills/mycroft-npr-news.mycroftai/__init__.py", line 50, in initialize
    self.on_websettings_changed()
  File "/opt/mycroft/skills/mycroft-npr-news.mycroftai/__init__.py", line 78, in on_websettings_changed
    create_custom_station(custom_url)
  File "/opt/mycroft/skills/mycroft-npr-news.mycroftai/stations/station.py", line 146, in create_custom_station
    is_rss_feed = feedparser.parse(station_url).entries > 0
TypeError: '>' not supported between instances of 'list' and 'int'
`

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 4
 - OS: Picroft
 - Mycroft-core version: 21.2.2

**Additional context**
I tried to set up a custom new source but reverted back to the default files. Things worked for awhile until I did this. Now I can't get it to work again, even though I've reverted back to the 21.02 branch.
I suspect that it's getting a bad setting from home.mycroft.ai, but I can't access the News settings there anymore to revert the setting back to the default. I'm stuck.

**Comment by krisgesling** [comment]
Hey, thanks for logging this - there's a fix committed in the PR above. If you are able to confirm it that is great, otherwise it will take a few days to push it out to all devices.
