### ISSUE TITLE
url_rss NoneType

### ISSUE THREAD

**Issue by tlc** [MycroftAI/skill-npr-news#14]
```
Traceback (most recent call last):
  File "/home/mycroft/mycroft-core/mycroft/skills/core.py", line 123, in load_skill
    skill._register_decorated()
  File "/home/mycroft/mycroft-core/mycroft/skills/core.py", line 460, in _register_decorated
    method = getattr(self, attr_name)
  File "/opt/mycroft/skills/skill-npr-news/__init__.py", line 44, in url_rss
    if "not_set" in pre_select:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by forslund** [comment]
This has been resolved now. Closing the issue. If you still experience issues feel free to reopen it.
