### ISSUE TITLE
Failed to load skill: skill-npr-news

### ISSUE THREAD

**Issue by jandrioli** [MycroftAI/skill-npr-news#30]
Traceback (most recent call last):
  File "/home/carlos/mycroft-core/mycroft/skills/core.py", line 119, in load_skill
    ('.py', 'rb', imp.PY_SOURCE)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/skill-npr-news/__init__.py", line 21, in <module>
    from mycroft.skills.common_play_skill import CommonPlaySkill, CPSMatchLevel
ModuleNotFoundError: No module named 'mycroft.skills.common_play_skill'

**Comment by KathyReid** [comment]
Thanks @jandrioli for raising this - can I ask if you're on Picroft, Mark 1 or Mycroft for Linux?
Kind regards, 
Kathy

**Comment by jandrioli** [comment]
Hi Kathy
Im on mycroft for linux, kernel 4.14
Im using mycroft's dev branch ( not the stable one )


On Oct 19, 2018 19:21, Kathy Reid <notifications@github.com> wrote:

Thanks @jandrioli<https://github.com/jandrioli> for raising this - can I ask if you're on Picroft, Mark 1 or Mycroft for Linux?
Kind regards,
Kathy

**Comment by forslund** [comment]
@jandrioli is this still an issue?

Have you updated the dev branch at all? (`git pull`)

**Comment by penrods** [comment]
I'm assuming this was due to running an old version of mycroft-core.  Closing.
